language: node_js
node_js: 
- 14.12.0
cache: npm

install:
 - npm ci

script:
 - npm run test
 - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: gh-pages